/*jshint esversion: 6 */

const SET_AUTH_USER = 'SET_AUTH_USER';
const FLIP_TRANSPARENT_BACKGROUND_STATE = 'FLIP_TRANSPARENT_BACKGROUND_STATE';

export {
    SET_AUTH_USER,
    FLIP_TRANSPARENT_BACKGROUND_STATE,
};
